name: dolumns
description: A Dart library for formatting text output into columns. Useful for printing tabular data in a terminal.
version: 2.0.1
homepage: https://github.com/maks/dolumns

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.2

topics:
 - formatting
 - cli
 - strings