name: dolumns
description: A Dart library for formatting text output into columns. Useful for printing tabular data in a terminal.
version: 2.0.0-nullsafety.0
homepage: https://github.com/maks/dolumns

environment:
  sdk: ">=2.12.0-133.2.beta <3.0.0"

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
