name: dolumns
description: A library for formatting text output into columns.
version: 1.0.0
homepage: https://github.com/maks/dolumns

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
